title: 중력파 및 수치상대론 연구자 그룹
description: 중력파 및 수치상대론 연구자 그룹의 홈페이지입니다.

#baseurl: /business-frontpage
#color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"
color-scheme: "#0275d8" # This is a HEX code for the primary color in bootstrap 4.

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _posts

exclude:
  - .sass-cache

timezone: Asia/Seoul

#new_badge 이후에 new 배지가 게시물 제목에서 사라짐
new_badge: 3